// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyyrjgtmzgcstcxzhqow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5eXJqZ3Rtemdjc3RjeHpocW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDQxMzUsImV4cCI6MjA3MjIyMDEzNX0.L2yAqHbxVAXwjXCplMppblgOe72A06OyZS-rpnGH11w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});